services:
  # フロントエンド (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "5173:5173"
      - "3001:3001"
      - "6006:6006"
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8080
    # セキュリティ設定（開発環境用）
    read_only: false   # 開発環境では書き込み必要
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - DAC_OVERRIDE  # ファイル権限の読み取り・書き込みに必要
    depends_on:
      - backend
    networks:
      - family-budget-network

  # バックエンド (Go)
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - GO_ENV=development
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=family_budget
      - DB_USER=app_user
      - DB_PASSWORD=app_password
    # セキュリティ設定
    read_only: false   # 開発環境では書き込み必要
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE  # ポート8080バインドに必要
    depends_on:
      - db
    networks:
      - family-budget-network
    restart: unless-stopped

  # データベース (MySQL)
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=family_budget
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
    volumes:
      - mysql_data:/var/lib/mysql
    # セキュリティ設定
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    networks:
      - family-budget-network
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped


volumes:
  mysql_data:

networks:
  family-budget-network:
    driver: bridge